#!/bin/sh

GITEA_BASE_URL="https://git.mills.io/prologic/zs-starter-template/_edit/main"

url="${GITEA_BASE_URL}/${ZS_FILE}"

printf "<a href=\"%s\" rel=\"nofollow\" target=\"_blank\">✍️ Edit this page on Gitea.</a>" "$url"
