#!/bin/sh

set -e

CSS="simple style"
JS="live"

for css in $CSS; do
  minify -o "$ZS_OUTDIR/css/$css.min.css" "$ZS_OUTDIR/css/$css.css"
done

for js in $JS; do
  minify -o "$ZS_OUTDIR/js/$js.min.js" "$ZS_OUTDIR/js/$js.js"
done
