#!/bin/sh

set -e

CSS="bahunya site"
CSS="$CSS toastui toastui-dark"
CSS="$CSS tui-color-picker toastui-editor-plugin-color-syntax"
CSS="$CSS prism toastui-editor-plugin-code-syntax-highlight"

for css in $CSS; do
    printf "<link rel=\"stylesheet\" href=\"/assets/css/%s.css\">\n" "$css"
done
